msp: hdmi: add missing c8051_hdcp22_program.bin file
Due to .gitignore settings, this binary file was missing from the
initial MSP file import.  Let's add it to fix the following build error.

  CC      drivers/msp/hdmi/hdmi_2_0/hal/ctrl/imagev200/hdmi_hal.o
drivers/msp/hdmi/hdmi_2_0/hal/ctrl/imagev200/hdmi_hal.c:663:40: fatal error: c8051_hdcp22_program.bin: No such file or directory
     #include "c8051_hdcp22_program.bin"

Signed-off-by: Shawn Guo <shawn.guo@linaro.org>